[workspace]
members = ["py"]
default-members = [".", "py"]

[workspace.package]
version = "0.1.20"
edition = "2024"

[package]
name = "fastpylight"
version.workspace = true
edition.workspace = true
rust-version = "1.91"

[lib]
name = "fastpylight"

[features]
default = ["standard-languages", "themes"]
standard-languages = [
    "lumis/lang-bundle-web",
    "lumis/lang-bundle-web-extra",
    "lumis/lang-bundle-system",
    "lumis/lang-bundle-backend",
    "lumis/lang-r",
    "lumis/lang-powershell",
    "lumis/lang-lua",
    "lumis/lang-matlab",
    "lumis/lang-perl",
    "lumis/lang-pascal",
    "lumis/lang-fortran",
    "lumis/lang-objc",
    "lumis/lang-julia",
    "lumis/lang-swift",
]
all-languages = ["lumis/all-languages"]
themes = []

[dependencies]
lumis = { version = "0.12", default-features = false }
thiserror = "2"

[lints.clippy]
too_many_arguments = "allow"

[profile.test]
inherits = "release"

[profile.release]
lto = false
codegen-units = 16

[profile.release.package.fastpylight]
incremental = true

[profile.release.package.fastpylight-py]
incremental = true

[profile.dist]
inherits = "release"
lto = true
incremental = false
codegen-units = 1
strip = true

[profile.dist.package.fastpylight]
incremental = false

[profile.dist.package.fastpylight-py]
incremental = false
